function list_global_observation_params = get_global_observation_params
% list of params which are valid for all channels

list_global_observation_params = {'sampling_frequency', 'scan_length', 'station_name', ...
    'station_name_trf_coord', ...
    'number_of_bits', 'recorder_transport_type_name', 'mode_observation', ...
    'date_vec', 'source_name', 'frame_length_byte', ...
    'header_length_byte', 'vdif_version_number', 'experiment_name', ...
    'vex_file_format', 'experiment_description', 'user_name', 'target_corr', ...
    'site_type', 'station_name_8character', 'site_position_ref', 'occupation_code', ...
    'source_type', 'ref_coord_frame', 'polarization', 'IF_sideband', ...
    'obs_sideband_vex', 's_crf', 'X_trf'};

end

