function Hd = hilbert_filter_design
%HILBERT_FILTER_DESIGN Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.5 and DSP System Toolbox 9.7.
% Generated on: 23-Jun-2020 16:36:43

% Equiripple Hilbert transformer filter designed using the FIRPM function.

% All frequency values are normalized to 1.

N = 50;         % Order
F = [0.1 0.9];  % Frequency Vector
A = [1 1];      % Amplitude Vector
W = 1;          % Weight Vector

b  = firpm(101, [0.1 0.9], [1 1], 1, 'hilbert');


% [EOF]
